### ISSUE TITLE
 Unable to integrate cucumber html reporter

### ISSUE THREAD

**Issue by bijivelayudhan** [spirosikmd/cucumber-puppeteer-example#1]
installed cucumber html reporter using
npm i cucumber-html-reporter

But unable to see the html report with screenshot

**Comment by spirosikmd** [comment]
@bijivelayudhan as we are using cucumber-js so we [first need to generate a JSON report and then use this as a source for the HTML reporter](https://www.npmjs.com/package/cucumber-html-reporter#for-cucumberjs). I merged an example, I hope it is useful!
