### ISSUE TITLE
Running yarn test after installing all dependencies gives timeout error

### ISSUE THREAD

**Issue by erashish11** [spirosikmd/cucumber-puppeteer-example#11]
C:\Users\Ashish\Downloads\cucumber-puppeteer-example-master>yarn test
yarn run v1.16.0
$ cucumber-js -f json:cucumber_report.json
F----.

Failures:

1) Scenario: add todo # features\page.feature:6
   × Before # features\support\steps.js:3
       Error: function timed out, ensure the promise resolves within 5000 milliseconds
           at Timeout._time.default.setTimeout [as _onTimeout] (C:\Users\Ashish\Downloads\cucumber-puppeteer-example-master\node_modules\cucumber\lib\user_code_runner.js:81:20)
           at ontimeout (timers.js:436:11)
           at tryOnTimeout (timers.js:300:5)
           at listOnTimeout (timers.js:263:5)
           at Timer.processTimers (timers.js:223:10)
   - Given I have a todo "clean the kitchen" # features\support\steps.js:11
   - When I write the todo in the input field # features\support\steps.js:15
   - And I click enter # features\support\steps.js:19
   - Then I expect to see the todo in the list # features\support\steps.js:23
   √ After # features\support\steps.js:7

1 scenario (1 failed)
4 steps (4 skipped)
0m05.722s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\Ashish\Downloads\cucumber-puppeteer-example-master>

**Comment by abraham** [comment]
You might receive this if `http://todomvc.com/examples/react/#/` is being slow.

**Comment by spirosikmd** [comment]
I also get timeouts sometimes, probably due to todomvc.com being slow as @abraham mentioned! The default timeout is 5 seconds, so this could be solved by increasing the timeout I guess. I am closing this issue for now @erashish11.

**Comment by erashish11** [comment]
> I also get timeouts sometimes, probably due to todomvc.com being slow as @abraham mentioned! The default timeout is 5 seconds, so this could be solved by increasing the timeout I guess. I am closing this issue for now @erashish11.

Thanks
