### ISSUE TITLE
headless is not working

### ISSUE THREAD

**Issue by bijivelayudhan** [spirosikmd/cucumber-puppeteer-example#7]
Unable to run headless.. showing timeout

**Comment by bijivelayudhan** [comment]
F----.

Failures:

1) Scenario: add todo # features\page.feature:6
   × Before # features\support\steps.js:3
       Error: function timed out, ensure the promise resolves within 5000 milliseconds
           at Timeout._time.default.setTimeout [as _onTimeout] (D:\cucumber-puppeteer-example\node_modules\cucumber\lib\user_code_runner.js:81:20)
           at ontimeout (timers.js:436:11)
           at tryOnTimeout (timers.js:300:5)
           at listOnTimeout (timers.js:263:5)
           at Timer.processTimers (timers.js:223:10)
   - Given I have a todo "clean the kitchen" # features\support\steps.js:11
   - When I write the todo in the input field # features\support\steps.js:15
   - And I click enter # features\support\steps.js:19
   - Then I expect to see the todo in the list # features\support\steps.js:23
   √ After # features\support\steps.js:7

1 scenario (1 failed)
4 steps (4 skipped)
0m05.255s
npm ERR! Test failed.  See above for more details.

**Comment by spirosikmd** [comment]
Hi @bijivelayudhan! I am not sure exactly what you mean. The example project runs the `cucumber-js` command headless when you execute `yarn test`. Can you create a reproducible example?

**Comment by spirosikmd** [comment]
@bijivelayudhan this is probably related to #11. I am closing this issue for now!
